language: php
dist: bionic

php:
    - 7.0
    - 7.1
    - 7.2
    - 7.3

install:
    - sudo apt-get install libwebkitgtk-3.0-dev libgconf2-dev libgstreamer1.0-dev libsdl1.2-dev libgtk-3-dev

script: phpize && ./configure && make && make test

after_failure: cat wxWidgets-*/mybuild/config.log

notifications:
    irc:
        channels:
            - "irc.freenode.net#wxphp"
        skip_join: true
